# Generated by Django 3.2 on 2021-05-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='pub_date',
            new_name='publication_date',
        ),
        migrations.AddField(
            model_name='report',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_comment',
            field=models.CharField(max_length=255, verbose_name='Комментарий к отчету'),
        ),
    ]
