# Generated by Django 3.2 on 2021-05-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210519_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего редактирования'),
        ),
    ]
