# Generated by Django 3.2 on 2021-05-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_report_last_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='last_modified',
        ),
        migrations.AddField(
            model_name='report',
            name='greenhouse',
            field=models.BigIntegerField(default=0, verbose_name='Номер теплицы'),
        ),
        migrations.AddField(
            model_name='report',
            name='production_department',
            field=models.BigIntegerField(default=0, verbose_name='Номер производственного отделения'),
        ),
    ]
