# Generated by Django 3.2.5 on 2021-07-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.FilePathField(default='', verbose_name='Применение к'),
        ),
    ]
