# Generated by Django 3.2.5 on 2021-07-20 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0004_alter_menu_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-url']},
        ),
    ]
