# Generated by Django 3.2.5 on 2021-08-03 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0005_alter_menu_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-url'], 'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Отчет', 'verbose_name_plural': 'Отчеты'},
        ),
    ]
