# Generated by Django 3.2.5 on 2021-08-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0007_auto_20210809_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='measurement_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
