# Generated by Django 3.2.5 on 2021-08-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0008_alter_report_measurement_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culture_name', models.CharField(max_length=50, verbose_name='Название культуры')),
            ],
            options={
                'verbose_name': 'Культура',
                'verbose_name_plural': 'Культуры',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='culture',
            field=models.CharField(default='', max_length=50, verbose_name='Культура / гибрид'),
        ),
        migrations.AlterField(
            model_name='report',
            name='greenhouse',
            field=models.BigIntegerField(verbose_name='Номер теплицы'),
        ),
        migrations.AlterField(
            model_name='report',
            name='production_department',
            field=models.BigIntegerField(verbose_name='Номер производственного отделения'),
        ),
    ]
