# Generated by Django 3.2.5 on 2021-08-09 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0009_auto_20210809_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cultures',
            options={'verbose_name': 'Культуры', 'verbose_name_plural': 'Культуры'},
        ),
        migrations.RemoveField(
            model_name='cultures',
            name='id',
        ),
        migrations.AlterField(
            model_name='cultures',
            name='culture_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Название культуры'),
        ),
        migrations.AlterField(
            model_name='report',
            name='culture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.cultures', verbose_name='Культура / гибрид'),
        ),
    ]
