# Generated by Django 3.2.5 on 2021-08-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0010_auto_20210809_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthStages',
            fields=[
                ('growth_stage', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Стадия роста')),
            ],
            options={
                'verbose_name': 'Стадия роста',
                'verbose_name_plural': 'Стадии роста',
            },
        ),
        migrations.AlterModelOptions(
            name='cultures',
            options={'verbose_name': 'Культуру', 'verbose_name_plural': 'Культуры'},
        ),
    ]
