# Generated by Django 3.2.5 on 2021-08-09 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0011_auto_20210809_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='growth_stage',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Reports.growthstages', verbose_name='Стадия роста'),
        ),
        migrations.AlterField(
            model_name='report',
            name='culture',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Reports.cultures', verbose_name='Культура / гибрид'),
        ),
    ]
