# Generated by Django 3.2.5 on 2021-08-09 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0012_auto_20210809_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AlterField(
            model_name='report',
            name='culture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.cultures', verbose_name='Культура / гибрид'),
        ),
        migrations.AlterField(
            model_name='report',
            name='greenhouse',
            field=models.PositiveIntegerField(verbose_name='Номер теплицы'),
        ),
        migrations.AlterField(
            model_name='report',
            name='growth_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.growthstages', verbose_name='Стадия роста'),
        ),
        migrations.AlterField(
            model_name='report',
            name='measurement_date',
            field=models.DateField(verbose_name='Дата замера'),
        ),
        migrations.AlterField(
            model_name='report',
            name='production_department',
            field=models.PositiveIntegerField(verbose_name='Номер производственного отделения'),
        ),
    ]
