# Generated by Django 3.2.5 on 2021-08-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0013_auto_20210809_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['greenhouse', 'measurement_date'], 'verbose_name': 'Отчет', 'verbose_name_plural': 'Отчеты'},
        ),
    ]
