# Generated by Django 3.2.5 on 2021-08-11 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0014_alter_report_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='glazing_throughput',
            field=models.PositiveIntegerField(default='0', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Пропускная способность остекления (в процентах)'),
        ),
        migrations.AddField(
            model_name='report',
            name='light_intensity',
            field=models.PositiveIntegerField(default='0', verbose_name='Интенсивность естественного света'),
        ),
        migrations.AddField(
            model_name='report',
            name='light_intensity_per_day',
            field=models.PositiveIntegerField(default='0', verbose_name='Интенсивность естественного света (за световой день)'),
        ),
        migrations.AddField(
            model_name='report',
            name='lighting_system_operating_time',
            field=models.PositiveIntegerField(default='0', verbose_name='Количество часов работы системы досвечивания (50% вкл и откл берутся как 0,5 за 1 полный час)'),
        ),
        migrations.AddField(
            model_name='report',
            name='lighting_system_power',
            field=models.PositiveIntegerField(default='0', verbose_name='Мощность системы досвечивания'),
        ),
        migrations.AddField(
            model_name='report',
            name='lighting_system_turn_off_time',
            field=models.TimeField(default='00:00:00', verbose_name='Время отключения досвечивания'),
        ),
        migrations.AddField(
            model_name='report',
            name='lighting_system_turn_on_time',
            field=models.TimeField(default='00:00:00', verbose_name='Время включения досвечивания'),
        ),
        migrations.AddField(
            model_name='report',
            name='solar_radiation_per_day',
            field=models.PositiveIntegerField(default='0', verbose_name='Приход естественной солнечной радиации за сутки'),
        ),
        migrations.AddField(
            model_name='report',
            name='sunrise_time',
            field=models.TimeField(default='00:00:00', verbose_name='Время естественного восхода Солнца'),
        ),
        migrations.AddField(
            model_name='report',
            name='sunset_time',
            field=models.TimeField(default='00:00:00', verbose_name='Время естественного захода Солнца'),
        ),
        migrations.AddField(
            model_name='report',
            name='unlit_light_points',
            field=models.PositiveIntegerField(default='0', verbose_name='Количество негорящих светоточек'),
        ),
        migrations.AlterField(
            model_name='report',
            name='greenhouse',
            field=models.PositiveIntegerField(default='0', verbose_name='Номер теплицы'),
        ),
        migrations.AlterField(
            model_name='report',
            name='production_department',
            field=models.PositiveIntegerField(default='0', verbose_name='Номер производственного отделения'),
        ),
    ]
