# Generated by Django 3.2.5 on 2021-08-15 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0016_auto_20210813_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='sunrise_time',
            new_name='time_sunrise',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='sunset_time',
            new_name='time_sunset',
        ),
        migrations.AddField(
            model_name='report',
            name='CO2_avg_concentration_per_day',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Средняя концентрация в течении светового дня СО2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='CO2_end_time_supply',
            field=models.TimeField(default='00:00:00', verbose_name='Время окончания подачи СО2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='CO2_maximum_supply',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Макс. подача СО2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='CO2_start_time_supply',
            field=models.TimeField(default='00:00:00', verbose_name='Время начала подачи СО2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='DVP',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='ДВП'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='RH_day',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='ОВВ дневная'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='RH_night',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='ОВВ ночная'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='gas_measurements_carbon_monoxide',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Замеры отходящих газов с котельной - Угарный газ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='gas_measurements_nitrogen_dioxide',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Замеры отходящих газов с котельной - Азота диоксид'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='gas_measurements_nitrogen_oxide',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Замеры отходящих газов с котельной - Окись Азота'),
            preserve_default=False,
        ),
    ]
