# Generated by Django 3.2.5 on 2021-08-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0017_auto_20210815_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
