# Generated by Django 3.2.5 on 2021-08-16 06:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0019_alter_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='EC_irrigation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='EC поливное'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='EC_substrate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='EC в субстрате'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='PH_irrigation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Ph поливное'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='PH_mat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Ph  в мате'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='drainage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Дренаж'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='substrate_temp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Т субстрата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='water_availability',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Водообеспеченность на начало текущего дня'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='water_dropper_temp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Т поливной воды из под капельницы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='water_mixer_EC',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='EC поливной воды на миксере'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='water_mixer_temp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Т поливной воды на миксере'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='water_per_plant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Вылито воды на 1 растение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='watering_end_time',
            field=models.TimeField(default='00:00:00', verbose_name='Конец полива'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='watering_start_time',
            field=models.TimeField(default='00:00:00', verbose_name='Начало полива'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='weight_loss_mat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Потеря веса мата за ночь (ночная усушка)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='weight_loss_substrate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Потеря веса в субстрате между циклами'),
            preserve_default=False,
        ),
    ]
