# Generated by Django 3.2.5 on 2021-08-16 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0020_auto_20210816_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='crown_diameter',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Диаметр макушки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='flowering_plants_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество цветущих'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='fruit_avg_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Средний вес плод'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='fruits_on_plant',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество плодов на растении'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='growth_week',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Прирост за неделю'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='internode_number',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Число междоузлиев'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='leaf_blade_length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Длина листа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='leaf_blade_width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Ширина листа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='leaves_new_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество новых листьев'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='leaves_total_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество листьев на растении'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='non_standard_products_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='% нестандартной продукции'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='stem_diameter',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Диаметр стебля'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='total_plants_length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Общая длина растений'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='week_harvest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Урожай за неделю'),
            preserve_default=False,
        ),
    ]
