# Generated by Django 3.2.5 on 2021-08-16 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0021_auto_20210816_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='chemical_treatment',
            field=models.PositiveIntegerField(default=0, verbose_name='Химобработки совместимые'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='disease_infection',
            field=models.PositiveIntegerField(default=0, verbose_name='Зараженность болезнями'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='disease_infection_trips',
            field=models.PositiveIntegerField(default=0, verbose_name='Зараженность вредителями: ЗЦ трипс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='disease_infection_vermin',
            field=models.PositiveIntegerField(default=0, verbose_name='Зараженность вредителями: белокрылка, тля трипс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='disease_infection_virus',
            field=models.PositiveIntegerField(default=0, verbose_name='Зараженность болезнями: ВЗКМО, вирусы, бактериозы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='foliar_treatments',
            field=models.PositiveIntegerField(default=0, verbose_name='Внекорневые обработки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='pollination',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Опыление'),
            preserve_default=False,
        ),
    ]
