# Generated by Django 3.2.5 on 2021-08-16 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0022_auto_20210816_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='calcium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Кальций'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='chlorides',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Хлориды'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='electrical_conductivity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Электропроводность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='magnesium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Магний'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='nutrient_solution_calcium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Содержание кальция в питательном растворе'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='nutrient_solution_chlorine',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Содержание хлора в питательном растворе'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='nutrient_solution_magnesium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Содержание магния в питательном растворе'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='nutrient_solution_nitrate_nitrogen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Содержание нитратного азота в питательном растворе'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='nutrient_solution_phosphorus',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Содержание фосфора в питательном растворе'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='nutrient_solution_potassium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Содержание калия в питательном растворе'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='sodium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Натрий'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='total_alkalinity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Общая щелочность'),
            preserve_default=False,
        ),
    ]
