# Generated by Django 3.2.5 on 2021-08-20 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0023_auto_20210816_1249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
