# Generated by Django 3.2 on 2021-05-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_comment', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(verbose_name='Дата создания отчета')),
            ],
        ),
    ]
